### ISSUE TITLE
TypeError: fs.writeFile is not a function

### ISSUE THREAD

**Issue by RyanMitchellWilson** [jprichardson/node-jsonfile#105]
Just installed this and got this error as soon as I tried to use writeFile:
`108 |   fs.writeFile(file, str, options, callback)` in file `node_modules/jsonfile/index.js`

I tried removing all node_modules then reinstalling with no luck.

My usage:
```
jsonfile.writeFile('foo.json', this.jsonData, err => {
  console.error(err)
})
```

React: 16.2.0
jsonfile: 4.0.0

**Comment by RyanZim** [comment]
Are you using this in Node.js or the browser?

**Comment by ncking** [comment]
Semicolon!

**Comment by RyanZim** [comment]
Closing for lack of response.
