### ISSUE TITLE
Add an option to write a final newline

### ISSUE THREAD

**Issue by remss** [jprichardson/node-jsonfile#115]
The final newline to the files produced should be optional.

    jsonfile.writeFile(file, obj, { finalEOL: false  })

**Comment by RyanZim** [comment]
What is the usecase for not wanting a final EOL?

**Comment by remss** [comment]
Projects may have a .editorconfig with `insert_final_newline = false`, and nodejs script that generates files, currently using `fs.writeFile(path, JSON.stringify(data, null, 4))`.
So I cannot use `jsonfile.writeFile(path, data, {space: 4})` now because it will add a final EOL that is not wanted.

An other reason is a library produce json files with no final EOL. When you start using node-jsonfile module internally, you don't want to change the behavior or your API.

**Comment by RyanZim** [comment]
I don't really get the point of this since final EOLs are a strong Unix convention; but I would consider it if someone did a PR.

**Comment by asingh04** [comment]
@RyanZim i would like to pick this up

**Comment by RyanZim** [comment]
@asingh04 go for it.

**Comment by asingh04** [comment]
The PR for this feature:
https://github.com/jprichardson/node-jsonfile/pull/137
