### ISSUE TITLE
Provide methods which returns promises

### ISSUE THREAD

**Issue by Johann-S** [jprichardson/node-jsonfile#123]
Hi @jprichardson,

Thanks for your lib 👍 

I think it would be useful to provide methods which return a promise, what do you think ?

**Comment by RyanZim** [comment]
`jsonfile` already uses https://www.npmjs.com/package/universalify If you don't pass a callback, a promise will be returned.

**Comment by Johann-S** [comment]
Oh you're right thanks 👍
