### ISSUE TITLE
Uncaught TypeError: fs$readFile is not a function with webpack in react typescript web application

### ISSUE THREAD

**Issue by anandkrishna93** [jprichardson/node-jsonfile#127]
Hi Team,

I am getting **"Uncaught TypeError: fs$readFile is not a function"** issue while running **reactjs** **typescipt** app with **webpack**,

**Uncaught TypeError: fs$readFile is not a function
at go$readFile (graceful-fs.js:110)
at Object.readFile (graceful-fs.js:107)
at Object.readFileWithCallback (index.js:27)
at Object.readFileWithCallback [as readFile] (index.js:5)**

and when I am running same with **electron-webpack** it is working fine, not giving any error.

Please tell me the solution or any alternate way.

**Comment by RyanZim** [comment]
Are you running this in a browser?

**Comment by anandkrishna93** [comment]
Yes @RyanZim , I am trying to run in browser, actually currently the application is running as a windows app using electron-webpack, I want to run in browser.

**Comment by RyanZim** [comment]
`jsonfile` will not work in a browser, it needs access to the filesystem

**Comment by anandkrishna93** [comment]
Thank you @RyanZim , Can you please give any suggestion what we can use to access file system which will support in browser,

**Comment by RyanZim** [comment]
You cannot access the filesystem from a browser
