### ISSUE TITLE
Can this be made to write data to the browser instead of  just to the console?

### ISSUE THREAD

**Issue by Overbrd** [jprichardson/node-jsonfile#132]

**Comment by RyanZim** [comment]
`jsonfile` is for use in Node.js, not in the browser, so I'm not sure I understand the question?

**Comment by Overbrd** [comment]
I am looking to take a live JSON feed of data and format the data to display on a web page. 

Have a great day!

Matt Lind

**Comment by RyanZim** [comment]
Yeah, this isn't the module you want for that.

**Comment by Overbrd** [comment]
Any idea one that may work for me please? Or how it is done?

Have a great day!

Matt Lind

**Comment by RyanZim** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch is probably a good starting point.

**Comment by Overbrd** [comment]
Thank you. All the best. 

Have a great day!

Matt Lind
