### ISSUE TITLE
Invalid JSon after appending new object

### ISSUE THREAD

**Issue by LUK3D** [jprichardson/node-jsonfile#134]
jsonfile.writeFileSync(file, obj, { flag: 'a', spaces: 2 }) give an invalid json. Theres no coma between two objects

![image](https://user-images.githubusercontent.com/31851972/81753871-ac0c6280-94ac-11ea-8841-19330294f36b.png)

**Comment by RyanZim** [comment]
The append option will produce Newline-delimited JSON, which cannot be read by this module.

**Comment by i-break-codes** [comment]
@RyanZim then what's the point of readySync option when it doesn't support file read?

**Comment by RyanZim** [comment]
It reads normal JSON, not Newline-delemited JSON
