### ISSUE TITLE
Is there any reason for adding a  final EOL 

### ISSUE THREAD

**Issue by sinikami** [jprichardson/node-jsonfile#135]
```javascript
function stringify (obj, options = {}) {
  const EOL = options.EOL || '\n'

  const str = JSON.stringify(obj, options ? options.replacer : null, options.spaces)

  return str.replace(/\n/g, EOL) + EOL
}
```

Add a new EOL makes it different with origin source.

I saved  hash  in JSON.stringify(...), but it is different with hashing from file because of a final EOL was added.

**Comment by RyanZim** [comment]
Ending files with a newline is a strong Unix/git convention, and I don't think we should deviate from it.
