### ISSUE TITLE
Getting error with Electron App

### ISSUE THREAD

**Issue by sadashivm** [jprichardson/node-jsonfile#141]
Helo @RyanZim ,
I'm using this plugin with Electron only. I got the below error,

![image](https://user-images.githubusercontent.com/10355473/101331493-15652000-389a-11eb-9f1a-6d60b9c08b77.png)

Here is my code,

![image](https://user-images.githubusercontent.com/10355473/101331589-37f73900-389a-11eb-9231-e40b0bb6ab82.png)

NOTE:  Book.js and data.json files are in the same folder and I have used react js for coding.

Could you please tell the reason?

**Comment by RyanZim** [comment]
Let's keep this all in https://github.com/jprichardson/node-jsonfile/issues/140.
