### ISSUE TITLE
Bump graceful-fs version

### ISSUE THREAD

**Issue by bfaf** [jprichardson/node-jsonfile#143]
Could you bump graceful-fs version to 4.2x because version 4.1.x have memory leak issue when used with Jest?

Here link with more info about the problem:

[https://github.com/facebook/jest/issues/6399#issuecomment-399888409](https://github.com/facebook/jest/issues/6399#issuecomment-399888409)

**Comment by RyanZim** [comment]
The `graceful-fs` version is specified with `^`, so it should install 4.2.x unless your lockfile is too restrictive.
