### ISSUE TITLE
readFile throws even if throws is set to false

### ISSUE THREAD

**Issue by modten** [jprichardson/node-jsonfile#152]
fs.readFileSync has been moved within the try/catch, but readFile has not

https://github.com/jprichardson/node-jsonfile/issues/47

**Comment by RyanZim** [comment]
This is basically a dupe of https://github.com/jprichardson/node-fs-extra/issues/542; it's not clear what the way forward is.

**Comment by modten** [comment]
ok, i will use the sync api
