### ISSUE TITLE
Add simple caching functionallity

### ISSUE THREAD

**Issue by tkhduracell** [jprichardson/node-jsonfile#20]
How about adding a simple caching mechanism?
```js
var json = js.readFileSync('/path', {expire: 3600} );
```

**Comment by jprichardson** [comment]
What does it mean to `expire`? The object would be set to `null` after expiration?

**Comment by tkhduracell** [comment]
Yes, essentially. The file would be read from filesystem again, when `js.readFileSync` is called. Could be handy in my view. Maybe it is out of the scope of this project though.

**Comment by jprichardson** [comment]
Yeah, I think this is out of scope. This could easily be done in a library that builds upon `json-file`.
