### ISSUE TITLE
Default value for spaces in readme.md is outdated

### ISSUE THREAD

**Issue by sebakerckhof** [jprichardson/node-jsonfile#22]
Since https://github.com/jprichardson/node-jsonfile/pull/16 , the default value for spaces is null (so no formatting).

However, the readme.md file still says the default value is 2. This got me confused when I saw formatting was lost.

**Comment by jprichardson** [comment]
Excellent point. I'm going to modify the options so that you can you pass in the spacing/formatting along with each method call.

**Comment by adambuczynski** [comment]
+1 :)
