### ISSUE TITLE
readFile: Passing in null options with a callback throws an error

### ISSUE THREAD

**Issue by AndrewDicks** [jprichardson/node-jsonfile#24]
When invoking readFile, if you pass in null for the options object, and also pass in a callback, line 14 in index.js throws a "cannot read property reviver of null" exception.  This is a new bug since the recent addition of the "reviver" parameter.

**Comment by jprichardson** [comment]
Oops! I'm on it. Thanks for reporting.

**Comment by jprichardson** [comment]
Published 2.1.1. Thanks again!

**Comment by AndrewDicks** [comment]
No worries - thanks for the super-prompt response!
