### ISSUE TITLE
Breaking change to fs-extra

### ISSUE THREAD

**Issue by raymondfeng** [jprichardson/node-jsonfile#26]
The commit https://github.com/jprichardson/node-jsonfile/commit/3ce00a504b11ee93af765916db8c75e88006a088 breaks https://github.com/jprichardson/node-fs-extra/blob/master/lib/index.js as `this.spaces` now refers to `fs.spaces` which is always undefined.

**Comment by jprichardson** [comment]
Ooops! Sorry, fixing...

**Comment by jprichardson** [comment]
Sorry about that. Published and fixed in `0.20.1`.

**Comment by jprichardson** [comment]
Gah, I made the fix in `fs-extra`... :(

**Comment by jprichardson** [comment]
I'm not sure if there's anything to fix here....

**Comment by jprichardson** [comment]
As of `jsonfile@2.2.0`, you can no explicitly set `spaces` in the methods `writeFile()` or `writeFileSync()`. Just pass in locally `{spaces: 2}`. All you'd need to do is reinstall your current version of `fs-extra` that supports `^jsonfile@2.0.0`.
