### ISSUE TITLE
How to use Jsonfile package in Meteor.js App?

### ISSUE THREAD

**Issue by phirum** [jprichardson/node-jsonfile#30]
Hello,
I want to use your package `jsonfile` in my meteor.js app, and use meteor package call `meteor add meteorhacks:npm` from using npm modules inside meteor app.
Do you have some guide line or example for do this?

**Comment by jprichardson** [comment]
Sorry, I've never used meteor before. From looking over https://github.com/meteorhacks/npm

My guess is to add `jsonfile` to your `package.json`:

**package.json**:

```js
{
  "jsonfile": "2.2.1"
}
```

**app.js**:
```js
var jsonfile = Meteor.npmRequire('jsonfile')
```

The documentation didn't say anything about actually installing npm modules. Presumably the same as with npm:

    npm i --save jsonfile@latest

Good luck!

**Comment by phirum** [comment]
I try this code, but It seems like it's no  working. 
thank you for you answer.

**Comment by tgoldenberg** [comment]
You can `var jsonfile = require('jsonfile')` with latest version of `Meteor`

**Comment by mpkliewer** [comment]
If you're using imports with Meteor ^=1.3.2.4, you can also use:
```
import jsonfile from 'jsonfile';
```

Behind the scenes, it's still using `require` but it's nice to keep syntax consistent if you're already using `import`.
