### ISSUE TITLE
Shorten the names of read/write functions

### ISSUE THREAD

**Issue by pinn3** [jprichardson/node-jsonfile#46]
`readFile` and `writeFile` feels kind of given, since the package is called jsonfile and it's purpose to handle files. The same goes for `writeFileSync`

Is there any reasoning for why the aren't called just `read` and `write`? The whole file suffix seems redundant otherwise.

**Comment by tankerkiller125** [comment]
@pinn3 I believe that the current names are used to conform with the standard that people expect from nodejs `fs` so that they don't need to remember that its different.

**Comment by RyanZim** [comment]
Yep, closing as per @tankerkiller125's comment.
