### ISSUE TITLE
Unit tests failed on Node.js 6.2.1

### ISSUE THREAD

**Issue by kuy** [jprichardson/node-jsonfile#48]
I noticed that node-jsonfile's unit tests failed on Node.js 6.2.1.
https://travis-ci.org/kuy/node-jsonfile/jobs/135610969

- [OK] v5.11.1
- [NG] v6.0.0
- [NG] v6.1.0
- [NG] v6.2.1

**Comment by kuy** [comment]
I'm working on this issue.
In v6.2.1, `rimraf()` doesn't execute the given callback function.
But rimraf passes unit tests without errors on v6.

### NG

```js
  beforeEach(function (done) {
    TEST_DIR = path.join(os.tmpdir(), 'jsonfile-tests-readfile-sync')
    rimraf(TEST_DIR, function () {
      fs.mkdir(TEST_DIR, done)
    })
  })

  afterEach(function (done) {
    rimraf(TEST_DIR, done)
  })
```

### OK

```js
  beforeEach(function (done) {
    TEST_DIR = path.join(os.tmpdir(), 'jsonfile-tests-readfile-sync')
    rimraf.sync(TEST_DIR)
    fs.mkdirSync(TEST_DIR)
    done()
  })

  afterEach(function (done) {
    rimraf.sync(TEST_DIR)
    done()
  })
```

**Comment by jprichardson** [comment]
Excellent, thanks for looking at this. PR accepted.

**Comment by kuy** [comment]
Already accepted? (or typo?) It doesn't look so...
Can I continue to tackle this issue and send PR?

**Comment by jprichardson** [comment]
> Can I continue to tackle this issue and send PR?

Yes, sounds great.
