### ISSUE TITLE
can't install node jsonfile

### ISSUE THREAD

**Issue by YounessBenmouloud** [jprichardson/node-jsonfile#51]
Hello, i have a project with angular2 beta then i want to overwrite some json file in javascript then i found node-jsonfile, the problem is i can't install it and too i want to know a simple usage.
when i put npm install jsonfile il have this error : 
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "jsonfile"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ENOSELF

npm ERR! Refusing to install jsonfile as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ADMyNE\Desktop\node-jsonfile-master\npm-debug.log
```
thanks

**Comment by RyanZim** [comment]
Your problem is that your module is named `jsonfile`. If you module is named `jsonfile`, you can't install the npm package `jsonfile`. Change the `name` field in the `package.json`, and it should install correctly.
