### ISSUE TITLE
obj.data ? How do I read specific element in json file?

### ISSUE THREAD

**Issue by Lazarus118** [jprichardson/node-jsonfile#54]
If I have a Json file say:

> {
>  "data": { 
>     "points" : "1",
>     "name": "Jones"
>     }
> }

How do I read "points" value?

**Comment by jprichardson** [comment]
```js
var jsonfile = require('jsonfile')
var file = 'myfile.json'

console.log(jsonfile.readFileSync(file).data.points)
```

**Comment by Lazarus118** [comment]
Okay but what if it's in the format :

> {
>   "data": [
>     {
>       "email": " ", 
>       "products": [ ], 
>       "username": " "
>     }, 
>     {
>       "email": " ", 
>       "products": [
>         {
>           "actual_food_amount": "15", 
>           "amount": "20", 
>           "drink": "Local Drink ", 
>           "food": "Dasheen meal w/ codfish", 
>           "id": 2, 
>           "location": "Orchard Restaurant"
>         } 
> ]
> }
>  }

and I want to read "food"
