### ISSUE TITLE
should include "fs" as a dependency

### ISSUE THREAD

**Issue by hobberwickey** [jprichardson/node-jsonfile#56]
I realize most everyone will have this already installed, but it is imported so you might want to add it as a dependency.

**Comment by jprichardson** [comment]
`fs` is not a 3rd part module, so why would it need to be a dependency?

**Comment by hobberwickey** [comment]
That's what I assumed too, but for some reason I needed to explicitly install it. Node v5.10.1

**Comment by jprichardson** [comment]
> That's what I assumed too

It's not an assumption. `fs` is part of Node.js core.

> but for some reason I needed to explicitly install it

You should figure out what that reason is.

**Comment by RyanZim** [comment]
As stated above, `fs` is a core module; no need to depend on it. Closing.
