### ISSUE TITLE
Problem in read JSON

### ISSUE THREAD

**Issue by aribs** [jprichardson/node-jsonfile#59]
Hi, i have this code:
var outputData = jsonfile.readFileSync(outputFile);
console.dir(outputData);

In the outputData one example of content:
id": 76869196581463**6545**,(look this last 4 characters)
      "is-retweet": false,
.......

In console.dir(outputData); i get this for the same value:
"id": 76869196581463**6500**,
      "is-retweet": false,
.......

In all objects in json, only change the last 4 characters of ID, other attribs works ok

Any idea?

Thanks

**Comment by jprichardson** [comment]
Not sure. This seems like a domain specific problem?

**Comment by aribs** [comment]
It could be by the size of the number?

**Comment by jprichardson** [comment]
Oh, that's probably it. JS only supports up to 53 bit integers. I'm assuming the JSON parser is choking on that. Use strings for your numbers?

**Comment by aribs** [comment]
Thanks, fixed. I changed 'ID' for String
