### ISSUE TITLE
Error when running on windows

### ISSUE THREAD

**Issue by Egoscio** [jprichardson/node-jsonfile#60]
Hello, I ran my code on my Mac and it worked fine, but when I send it to my friend who runs windows, he gets the following error:

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/3950951/18295364/9649777e-7455-11e6-89c2-b4147c26ea2b.png)

I tried doing a self diagnosis, and found the following issue with a related error: https://github.com/jprichardson/node-jsonfile/issues/40

Could [node-fs-extra](https://github.com/jprichardson/node-fs-extra) help?

The code in question writes to a directory with dynamically created files (I'm depending on jsonfile to create the files), so I assume fs-extra's outputJson will fix the whole issue, correct?

Thank you,

-- Egoscio

**Comment by jprichardson** [comment]
> I assume fs-extra's outputJson will fix the whole issue, correct?

Yes, it should.

**Comment by Egoscio** [comment]
@jprichardson Thank you for the quick reply. I was baffled because of how the error's presence was inconsistent across operating systems. I'll try to add that over to my friend's setup, and will report back / close the issue shortly.

**Comment by Egoscio** [comment]
Sorry for the delay, works perfectly fine now! Thanks @jprichardson !

**Comment by jprichardson** [comment]
Glad that it works!
