### ISSUE TITLE
writeFile doesn't work with some json

### ISSUE THREAD

**Issue by Pizylon** [jprichardson/node-jsonfile#61]
I tried to write a json like this:

[ live1: { block: '0.007',
    activation: '0.005',
    rangeB: '0.002',
    flashEnd: '0.006' },
  live2: { block: '0.007',
    activation: '0.005',
    rangeB: '0.002',
    flashEnd: '0.006' },
  live3: { block: '0.007',
    activation: '0.005',
    rangeB: '0.002',
    flashEnd: '0.006' }]

but the output is :
[]

it works if the JSON is like this:
[{      "name": "live1",
        "block": "0.007",
        "activation": "0.005",
        "rangeB": "0.002",
        "flashEnd": "0.006"
    },{
    "name": "live2",
    "block": "0.007",
    "activation": "0.005",
    "rangeB": "0.002",
    "flashEnd": "0.006"
    },{
        "name": "live3", 
        "block": "0.007", 
        "activation": "0.005", 
        "rangeB": "0.002", 
        "flashEnd": "0.006"
    }]

**Comment by jprichardson** [comment]
It's probably a domain specific problem? Can you break this down into code to reproduce the issue?

**Comment by Pizylon** [comment]
here is an example 
`function cheers()
{
    var arr=[];
  var data=  [
        {
            "name": "live1",
            "block": "0.007",
            "activation": "0.005",
            "rangeB": "0.002",
            "flashEnd": "0.006"
        },
        {
            "name": "live2",
            "block": "0.007",
            "activation": "0.005",
            "rangeB": "0.002",
            "flashEnd": "0.006"
        },
        {
            "name": "live3",
            "block": "0.007",
            "activation": "0.005",
            "rangeB": "0.002",
            "flashEnd": "0.006"
        }
    ];

    writeJson('no_error',data);

    for(var i=0;i<data.length;i++)
    {

        arr[data[i].name]={
            block :data[i].block,
            activation:data[i].activation,
            rangeB:data[i].rangeB,
            flashEnd:data[i].flashEnd
        };

    }
    console.log(arr);

    writeJson('with_error',arr);


}
`
and write file is 
`var jsonfile = require('jsonfile');


function writeJson(filename,json)
{

    var file = './json/'+filename+'.json';
    var obj =json;

    console.log('writing  '+filename);
    //console.log(json);
    jsonfile.writeFile(file, obj, function (err) {
        if(err)
        console.error(err)
    });



}`

**Comment by jprichardson** [comment]
It's because you're not reading the data in a callback. The second example you're using a callback, the first example you're not. Either use a callback or use the `sync` functions. Hope that helps.

**Comment by chaitan94** [comment]
The issue here is actually different, and actually rather a more silly mistake. writeFile failed for the first JSON you mentioned because its not actually a valid JSON.

The outermost brackets in **[**` live1: ... flashEnd: '0.006' }`**]** should actually be curly braces `{`. That is the valid JSON should have actually been **{**` live1: ... flashEnd: '0.006' }`**}**. Trying with this input, the code works as expected.

However I think that this still is an issue from the library side as well as when given such type of input it quietly writes '[]' inside the file without giving any error. This might make it easier for bugs to slip in, and harder for the programmer to debug.

**Comment by jprichardson** [comment]
> However I think that this still is an issue from the library side as well as when given such type of input it quietly writes '[]' inside the file without giving any error. This might make it easier for bugs to slip in, and harder for the programmer to debug.

Do you have a snippet reproducing this issue? Thanks!

**Comment by chaitan94** [comment]
You can try this snippet:

```javascript
var jsonfile = require("jsonfile");

var invalidJsonData = [];
invalidJsonData["key"] = "value";

console.log("Trying to save:");
console.log(invalidJsonData);

jsonfile.writeFile("/tmp/data", invalidJsonData, function(err) {
  if (err) {
    console.log("Error saving file: " + err);
  } else {
    console.log("File saved!");
  }

  jsonfile.readFile("/tmp/data", function(err, obj) {
    if (err) {
      console.log("Error reading file: " + err);
    } else {
      console.log("Read contents from file:")
      console.log(obj);
    }
  })
});
```

Here is the output I get:
```
Trying to save:
[ key: 'value' ]
File saved!
Read contents from file:
[]
```

As you can see we are not giving a valid json data per se, however there is no error / warning anywhere, and an empty array is stored in the file.

**Comment by jprichardson** [comment]
Hmmm... what would propose the generalized solution to be here given that `JSON.stringify` happily will stringify about anything and can't infer programmer intent?

**Comment by chaitan94** [comment]
I guess the root issue here is with the behavior of javascript itself. From the perspective of this library, I think the current behavior is correct and should be expected by the programmer. However, if you still see any more people accidentally using square brackets in the future, it might be a good idea to point this behavior out somewhere in the documentation as a note or FAQ.

**Comment by jprichardson** [comment]
> it might be a good idea to point this behavior out somewhere in the documentation as a note or FAQ.

Good idea, I would accept a PR if you're up for it.
