### ISSUE TITLE
writeFileSync does not seem to be writing correctly

### ISSUE THREAD

**Issue by LouiseMcMahon** [jprichardson/node-jsonfile#63]
I'm not 100% sure on the cause seems to be some encoding issue as files written by it on node 6.8.0 and latest version are appeared to be empty to node and notepad++, but Webstorm can read them fine.

This is on windows with node 6.8.0 and latest jsonfile.

**Comment by jprichardson** [comment]
Do you have a snippet to reproduce this issue? Thanks.

**Comment by RyanZim** [comment]
@LouiseMcMahon ping?

**Comment by LouiseMcMahon** [comment]
Feel Greek to close this I've got no idea how I solved this now sorry

On 25 April 2017 15:09:26 BST, Ryan Zimmerman <notifications@github.com> wrote:
>@LouiseMcMahon ping?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprichardson/node-jsonfile/issues/63#issuecomment-297042067

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
