### ISSUE TITLE
Appending to an existing JSON file:

### ISSUE THREAD

**Issue by Fenwil** [jprichardson/node-jsonfile#67]
If I do something like this: 

```var jsonfile = require('jsonfile')

var file = 'mods-installed.json'
var obj = {name: 'JP'}

jsonfile.writeFile(file, obj, {flag: 'a'}, function (err) {
  console.error(err)
})

jsonfile.writeFile(file, obj, {flag: 'a'}, function (err) {
  console.error(err)
})
```

If I already have something like this in my JSON file:

```
{
    "name": "LP"
}
```

I will get this:
```
{
    "name": "LP"
} {
    "name": "JP"
} {
    "name": "JP"
}
```

Is there a way to wrap all this objects in ONE object?

Thanks!

**Comment by jprichardson** [comment]
Yeah, you could use `Object.assign`... pinging @mawni - he may have had some good ideas here as well.

**Comment by Fenwil** [comment]
Thanks! I will try to solve it with Object.assign

**Comment by mawni** [comment]
yeah, if you want to have ONE object, I would go with `Object.assign` too.

**Comment by andela-anandaa** [comment]
If this wasn't solved, a shorter way could be, read the file in `obj`

Then update `obj` a you would like to e.g. `obj.name = "JP"` but remember this overwrites the previous `obj.name`, then do a write.

How does this sound?

**Comment by JacobDB** [comment]
I don't understand how to do this, can you give an example in code?

**Comment by RyanZim** [comment]
@JacobDB 

```js
const file = 'some.json'
const newData = { some: 'data' }
jsonfile.readFile(file, (err, oldData) => {
  if (err) console.error(err)
  jsonfile.writeFile(file, Object.assign(oldData, newData), err => {
    if (err) console.error(err)
    else console.log('done')
  })
})
```

Note that this only does a shallow clone of the data.

**Comment by hy9be** [comment]
The methods above cannot work with very large json, right?

**Comment by RyanZim** [comment]
@hy9be If you mean dealing with a file that's too large to be loaded in memory, yes. However, keep in mind, there's no good way to read a JSON file that big in Node.js.

**Comment by ailton-felix** [comment]
There is a way that worked perfectly for me:
[parse-large-json-file-in-nodejs](https://stackoverflow.com/questions/11874096/parse-large-json-file-in-nodejs/)
