### ISSUE TITLE
Support for 'modern' JSON (without quotes)

### ISSUE THREAD

**Issue by BaronChen** [jprichardson/node-jsonfile#69]
It seems like the library currently doesn't support 'modern' like:
`{
    foo : "foo"
}`

Is there a plan to support this?

**Comment by jprichardson** [comment]
```json
{ foo : "foo" }
```

Is not valid JSON AFAIK. Do you have a source for this?

**Comment by BaronChen** [comment]
Refer to http://json5.org/.
This is just a proposed extension to JSON. I don't think it is necessary to have. That's why I ask. 
Thanks.

**Comment by jprichardson** [comment]
I'm familiar with JSON5, but JSON5 is not JSON. I'd love it if JSON adopted features from JSON5, but until that happens, this library will keep things simple and just use JSON.
