### ISSUE TITLE
jsonfile.writeFile failed to write json file  

### ISSUE THREAD

**Issue by mehdi-alouane** [jprichardson/node-jsonfile#70]
jsonfile.writeFile failed to write json file , and everytime it's return `null` 
[need help!]
![screenshot from 2017-01-30 05 40 16](https://cloud.githubusercontent.com/assets/4208162/22413298/9a44ba16-e6ae-11e6-9b91-e8969e5cf1aa.png)

**Comment by jprichardson** [comment]
It's returning `null` because the `err` is null... Could you create a reproducible snippet?
