### ISSUE TITLE
Using steps for jsonfile module in Angular 2

### ISSUE THREAD

**Issue by daleep-croimedia** [jprichardson/node-jsonfile#80]
Can anyone tell me how to use jsonfile module, I'm new in Angular 2, I installed jsonfile module but not getting how to use it. Please help me to use it.
Thanks

**Comment by RyanZim** [comment]
@daleep-croimedia jsonfile is intended for use in Node.js. It's simply a convenience wrapper around the Node `fs` methods and javascript's `JSON` methods.

I'm not sure what you're trying to do, but you can't use this module in the browser.

**Comment by daleep-croimedia** [comment]
Yes sir I am using jsonfile in Node.js v7.6.0. But after install it I am getting error, the error is call is undefined in every function.

**Comment by RyanZim** [comment]
@daleep-croimedia Please post the code snippet that's giving you this error.
