### ISSUE TITLE
Writefile with serialisation error but no callback writes empty file

### ISSUE THREAD

**Issue by bergus** [jprichardson/node-jsonfile#81]
I'm pretty certain [the line](https://github.com/jprichardson/node-jsonfile/blob/38dadad0eb7e8c78022e4980fcba37a4fd4500ac/index.js#L97)
```js
if (callback) return callback(err, null)
```
in that `catch` block should be
```js
if (callback) callback(err, null)
return
```

**Comment by RyanZim** [comment]
@bergus You're right; can you submit a PR?

**Comment by bergus** [comment]
Nah, not interested, I was just looking at the code [for this SO question](https://stackoverflow.com/q/44573985/1048572).
