### ISSUE TITLE
Possibility to append JSON data to existing JSON file. 

### ISSUE THREAD

**Issue by niksmac** [jprichardson/node-jsonfile#84]
Can we add some elements to an already existing JSON file?

`my.json`

```
[
  {
    "name": "FY2017 Postage Services",
    "description": "NA"  
},
  {
    "name": "Rugged iPad Cases",
    "description": "NA"
  }
]
```

`my-new`

```
[
  {
    "name": "FY2037 Postage Services",
    "description": "NA"  
}
]
```

append `my-new` to `my.json` so that `my.json` becomes 

```
[
  {
    "name": "FY2017 Postage Services",
    "description": "NA"  
},
  {
    "name": "Rugged iPad Cases",
    "description": "NA"
  },
  {
    "name": "FY2037 Postage Services",
    "description": "NA"  
}
]
```

Makes any sense?

**Comment by RyanZim** [comment]
The exact implementation will vary depending on your data structure, for your case, you could do something like this:
```js
// Use jsonfile to read my.json & my-new; omitting for brevity
jsonfile.writeFile('my.json', myData.concat(myNewData), err => {
  // Handle error
})
```

**Comment by niksmac** [comment]
@RyanZim Not really what I asked. 

I was asking, what if `myData` is already written to the file and I am trying to append `myNewData` on the `nextTick`?

**Comment by RyanZim** [comment]
If `myData` is already written, it doesn't really make any difference; `writeFile` overwrites the existing file anyhow.

**Comment by niksmac** [comment]
I thinks it is duplicate to #52
