### ISSUE TITLE
replace \n with EOL

### ISSUE THREAD

**Issue by kellyselden** [jprichardson/node-jsonfile#87]
Would you be open to supporting native OS newlines? This would mean less newline processing in my tests because my fixture files in git have OS newlines already. Right now I'm doing something like

```js
fs.writeFileSync(filePath, JSON.stringify(value, null, 2).replace(/\n/g, EOL) + EOL));
```

to work cross-platform, but it would be great to just use this lib.

**Comment by jprichardson** [comment]
Yes, PR accepted, please include a test.
