### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kellyselden** [jprichardson/node-jsonfile#92]
Would you mind releasing #89?

**Comment by jprichardson** [comment]
@RyanZim please release this - should do major.

**Comment by RyanZim** [comment]
@jprichardson I assume kill 0.10, 0.12, & io.js support while we're at it?

**Comment by kellyselden** [comment]
It seems to me this is only additive, not breaking, so it could be a minor release. That way I can use it sooner in fs-extra without a major bump there.

**Comment by jprichardson** [comment]
>  I assume kill 0.10, 0.12, & io.js support while we're at it?

Yes.

**Comment by RyanZim** [comment]
jsonfile 4.0.0 released :tada: Will release in fs-extra as a patch release soon, hopefully tonight. Refs https://github.com/jprichardson/node-fs-extra/pull/491

**Comment by kellyselden** [comment]
Thanks @RyanZim

**Comment by RyanZim** [comment]
@kellyselden Released in fs-extra 4.0.2 :tada:

**Comment by RyanZim** [comment]
@estaub The info is in the CHANGELOG file: https://github.com/jprichardson/node-jsonfile/blob/master/CHANGELOG.md#400--2017-07-12
