### ISSUE TITLE
randomly getting error: “Unexpected token in JSON at position 0” using JSON.parse in Node with valid JSON

### ISSUE THREAD

**Issue by ezlbrmn** [jprichardson/node-jsonfile#94]
no changes to code. Pulling data from https://cloudpricingcalculator.appspot.com/static/data/pricelist.json which should be static as well (for duration of testing). Getting error at random times. 

```
C:\NODE.JS>node GCP_RatecardParser_v1.js
undefined:1
�
^

SyntaxError: Unexpected token  in JSON at position 0
    at Object.parse (native)
    at Request._callback (C:\NODE.JS\GCP_RatecardParser_v1.js:39:28)
    at Request.self.callback (C:\NODE.JS\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\NODE.JS\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\NODE.JS\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
```

**Comment by RyanZim** [comment]
Why are you using jsonfile when you're pulling from a URL?

**Comment by ezlbrmn** [comment]
Here is the portion of the code where I am using jsonfile module
request('https://cloudpricingcalculator.appspot.com/static/data/pricelist.json', function (error, response, body) {
  if (!error && response.statusCode == 200) {
             var importedJSON = JSON.parse(body);
              var JSON_str1 = JSON.stringify(importedJSON.gcp_price_list);
                JSON_str1=JSON_str1.replace("CP-COMPUTEENGINE-STORAGE-PD-CAPACITY", "CP_COMPUTEENGINE_STORAGE_PD_CAPACITY");
                var ezJSON = JSON.parse(JSON_str1);
                var STD_pd_disk = JSON.stringify(ezJSON.CP_COMPUTEENGINE_STORAGE_PD_CAPACITY.us);
                var STD_pd_disk  =STD_pd_disk*1;

                console.log('Standard persistent disks rate: ' + STD_pd_disk );




Thank you,

Eugene

**Comment by RyanZim** [comment]
You're using JavaScript's built-in JSON module, not jsonfile. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON

**Comment by ezlbrmn** [comment]
Thank you.


Eugene
